### ISSUE TITLE
Design UI to show users analysis findings

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/gpc-optmeowt#157]
Kiryl, I'm assigning this to you for the future even though we don't yet have enough data logged. The idea is to look at a large amount of logged privacy flag data, and from that data devise some method of giving the user a discrete and simple recommendation about their data- i.e., "we think this site sells your data" or "we think this site is complying". Warnings about selling data should *not* happen all the time, there should be some threshold- otherwise the user would have no reason to heed constant warnings on their favorite sites.

I think the 'algorithm' here should probably be pretty simple, even maybe as simple as coming up with some numerical threshold/percentage for allowed number of unset (falsy) data privacy flags.

**Comment by SebastianZimmeck** [comment]
> Warnings about selling data should not happen all the time, there should be some threshold- otherwise the user would have no reason to heed constant warnings on their favorite sites.

A few possibilities and comments.

- Log all (potential) violations to a background page. In addition, show the result for the current page in the popup --- violation or not. That way, it is up to the user whether they want to see what is going on (or go back to the logged violations in the background page).
- Alternatively/in addition, change the little green circle for the OptMeowt icon @kalicki1 introduced to yellow when we see a violation. E.g., currently it is turning briefly full green when visiting a site with `.well-known` (e.g., try for the NYTimes). Similarly, the icon could be briefly turning full yellow (red and green would not be ideal colors because they look the same grey for color-blind people).
- There is the usability issue of altert fatigue you mention, @stanleymarkman. Maybe the above could be some ways to address that. Another usability issue is that we may be sometimes not correct, e.g., we incorrectly detect a flag. We will have to figure out how often that happens. But the easiest way to resolve that point is to just include an explanation in the settings page or elsewhere that the analysis may be incorrect sometimes.

**Comment by SebastianZimmeck** [comment]
@stanleymarkman, I renamed this issue. Feel free to change with something that captures your idea better.

**Comment by stanleymarkman** [comment]
Sounds good- I think the final UI will end up being very similar to the ideas we discussed in lab meeting:

-First layer: simple color notification in the icon (with colorblind support)
-Second layer: a 1-2 sentence description in the Optmeowt dropdown, with a link to the background/settings page
-Third layer: Detailed breakdown of the privacy flags with specific resources linking to each legislation/implementation. For example: "This website ran 8 ad requests to Google AdSense without [Google's RDP setting]{https://support.google.com/adsense/answer/9598414?hl=en}, despite the GPC cookie being set."

There's two challenges I'll work on here: first, getting the UI to the point where it's giving the user useful info without constantly bothering them, which will require some testing; and second familiarizing myself with the Chrome/Firefox extension UI APIs.

**Comment by SebastianZimmeck** [comment]
Excellent, @stanleymarkman!

As this plan will likely require quite a number of changes, consider first bringing what you currently have into the main branch (issue #163). Feel free to decide however you see fit, though.

**Comment by SebastianZimmeck** [comment]
@kbeliauski suggested that the compliance analysis functionality works the way that a user can enter one or multiple websites to analyze, hit a start button, OptMeowt will then silently do the analysis (via headless browsing; is that possible?), and generate a report (say, a CSV file) with the analysis results. This change in functionality also necessitates a different approach to the UI.

I think we would need to further evolve the UI from what @stanleymarkman [described](https://github.com/privacy-tech-lab/optmeowt-browser-extension/issues/157#issuecomment-832021487). Essentially, the third layer could be what goes into the CSV file. The UI would be a button to start the analysis functionality, e.g., in the settings, some notification that the analysis is finished, an button for exporting the results (the functionality and design could be similar to the import and export of the domain list).

Maybe, this could be a separate Compliance Analysis Settings page (in addition to Settings, Domain List, and About). This Compliance Analysis Settings page would only be present in the Firefox version of OptMeowt (and, in terms of the codebase, is a separate Firefox module).

**Comment by kbeliauski** [comment]
I think that the way to go is, like @SebastianZimmeck said, to have a separate tab in the settings page for the multiple page analysis mode, but also keep a simpler version in the popup. The simpler version will just do what @stanleymarkman described and only for the website the user is currently on.

**Comment by SebastianZimmeck** [comment]
We can revive our [mockup](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/main/ui-mockup) folder and put the mockups there.

**Comment by kalicki1** [comment]
I drew up a quick sketch of a popup design specifically for the US privacy string analysis functionality. This is very flexible and final decisions are TBD but let's use this as a starting point. A lot more has been mentioned above on more intricate design ideas and for more flags, especially with a settings page, so this is definitely a small starting point. 

<img width="900" alt="Screen Shot 2021-08-17 at 7 44 34 PM" src="https://user-images.githubusercontent.com/60238705/129815481-a12417a6-8e5d-496d-b723-622f076b3ec6.png">
<img width="325" alt="Screen Shot 2021-08-17 at 7 44 40 PM" src="https://user-images.githubusercontent.com/60238705/129815473-084ce605-8218-4266-b359-c7d50e66383b.png">
<img width="400" alt="Screen Shot 2021-08-17 at 7 44 46 PM" src="https://user-images.githubusercontent.com/60238705/129815468-1a5ea999-4f1f-4a8f-9e5b-688ceac85112.png">

As a small note, I drew this up with a "browsing" use case in mind, where one site is visited and an analysis is done without any other input, so this may be reason to change the designs as well.

**Comment by SebastianZimmeck** [comment]
Nice!

- I like the `analysis` and `protection` labels and their symbols in Proposal 1. (As a side note, I feel the more prominently we advertise the analysis mode, the more flawless the transition from and to it has to be as it will be used more frequently.)
- Can users click on the `analysis` and `protection` labels? If so, what happens when they do?
- It seems you envision reusing in the `Analysis Breakdown` a good amount of structure and code that we already have in place for the approximately corresponding `Domain List`. That is great!
- Not sure if we need a separate `Analysis Settings` label/button. Maybe, this can be done through the normal top right settings icon. Maybe, if you are in the analysis popup, the link goes to the analysis settings page (or analysis section of  the settings page). And if you are in the protection popup, the link goes to the protection settings page (or protection section of the settings page).
- We also still need a mockup for the analysis page, which I think can be an extended or just bigger version of your Analysis Breakdown.

**Comment by OliverWang13** [comment]
Additionally, if 3rd party sites are counted in the CCPA compliant ration (4/15 in the mockup), it could artificially inflate the denominator. This issue could be circumnavigated by using a modified counting code or removing the ratio altogether.

**Comment by SebastianZimmeck** [comment]
@kalicki1 or @OliverWang13, do you have suggestions or a mockup for the analysis page? I imagine something along the lines of the domain list page.

**Comment by OliverWang13** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/82842273/129924669-c564e405-1ea5-4245-9068-ed8d462da3ae.png)

Here is my quick, roughly drawn mockup. I like the idea of having the domains with a drop down list that shows the specific information that is shown in the popup. @kalicki1 should also feel free to upload his own version.

**Comment by SebastianZimmeck** [comment]
@OliverWang13, that is a good! As you are showing it, we can reuse the code from the popup. On the left side, in addition to `Settings` and `About`, we would have `Domain List` and maybe `Compliance List` or something like that.

**Comment by kalicki1** [comment]
@OliverWang13, I am a fan of your options page mockup! I think we should shoot for something along those lines. 

@SebastianZimmeck, about your original thoughts on my popup mockup,

> Can users click on the analysis and protection labels? If so, what happens when they do?

I imagine them as buttons yes, and then assuming we have a perfect implementation, we can switch back and forth between analysis and protection mode as we discussed in our call. 

> Not sure if we need a separate Analysis Settings label/button. 

I agree with what you said for the most part, I thought that the `Analysis Settings` button could link to the analysis-specific options page as you said. This button could be renamed something along the lines of "more detailed breakdown," implying that users can get more info about that specific domain's analysis and others as well (which is what we will do according to @OliverWang13's mockup). 

@OliverWang13, about your points on my popup mockup,

>Another idea is that possibly after one of the step fails, all following steps could become grayed out to illustrate the order

I like this idea, we could also make sure to only generate our actions responsively until a step fails, then load the conclusion.

**Comment by SebastianZimmeck** [comment]
> I imagine them as buttons yes, and then assuming we have a perfect implementation, we can switch back and forth between analysis and protection mode ...

OK, yes, that would be great, indeed. Though, if it turns out to be too tricky, I am personally also fine with omitting the buttons and functionality. But, yes, give it a shot, and see how it goes. 

> I agree with what you said for the most part, I thought that the Analysis Settings button could link to the analysis-specific options page as you said.

OK, to keep it in the same style, in protection mode we should also have a button to the protection-specific options page (or domain list if we do not have a protection-specific options page).

**Comment by OliverWang13** [comment]
I think that having the analysis and protection labels being buttons could be a little complicated. Depending on our implementation, I am unsure how smoothly we could make the transition between them. Additionally, a portion of our users will have no use or interest for the analysis mode, so perhaps the way to switch could be a little less convenient, if that makes sense. I could see some users accidentally switching modes without knowing the difference and disrupting the functionality of the extension.

**Comment by SebastianZimmeck** [comment]
Let's discuss this later today.

**Comment by SebastianZimmeck** [comment]
In terms of the switching from analysis to protection mode or vice versa, let's not implement the buttons and functionality immediately. Maybe, we will do it later. 

In principle, the UI is good as is as shown in the mockup. Maybe, add some tooltips or do some smaller modifications.
