### ISSUE TITLE
Implement US Privacy string detection mechanism

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/gpc-optmeowt#158]
This feature will look at the intercepted HTTP headers/params in real time, giving the user a live, yet simplified and understandable picture of what a website is doing with their data.

The UI for this should be as simple and abstract as possible (probably giving a simple verbal statement about how we think a website is complying.) This doesn't have to be based just on live data- in the future, we could maybe aggregate data to give users a warning before they ever visit a site.

The algo needs to be fast enough to give a quick recommendation and to re-run every few HTTP requests. Should be fast as all the logging is slow enough already.

**Comment by SebastianZimmeck** [comment]
@stanleymarkman, see [my comment on the related issue](https://github.com/privacy-tech-lab/optmeowt-browser-extension/issues/157#issuecomment-831394601).

**Comment by SebastianZimmeck** [comment]
This issue is narrower than [initially described](https://github.com/privacy-tech-lab/optmeowt-browser-extension/issues/158#issue-873710407). The point is to implement a mechanism for detecting the [US Privacy String](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md#us-privacy-string-format) in HTTP requests. For example, we want to detect strings like `1YYN`. This detection is critical for our compliance analysis functionality: (1) we detect the US Privacy string value, (2) send a GPC signal, and (3) detect the US Privacy string value again to check whether it has changed, such that the user is now opted out.

The US Privacy string as specified by the IAB as technology-neutral. It can be in a header or an HTTP cookie, which is also just a header. So, generally, we should be able to see the string in the HTTP traffic. It may be that we can only do this for Firefox, though, as we may need to decrypt traffic, which is not easily possible on Chromium-based browsers. Initially, we should look into both.

Instead of using a header-based technology, some websites may also use a wrapper. We have a specific issue to address this point (#148). It would be good if we can identify the US Privacy string in those instances as well. However, if it is not possible or too challenging, it is OK to not do it as far as I am concerned. 

The definition of the privacy flags, including the US Privacy string, is in the [privacyFlags.js](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/main/src/data/privacyFlags.js). Note that there are various privacy flags in the file but we are only using the US Privacy String.

For reference: There are other closed related issues (#147, #154, and #159) superseded by this one.

**Comment by SebastianZimmeck** [comment]
@stanleymarkman will check if this is already done and act upon accordingly.

**Comment by stanleymarkman** [comment]
Closing this issue for now. It seems like right now the records stored of http requests including the US privacy string will only record a yes/no privacy selection. This means that the repurposed US Privacy parsing code will work for now.
