### ISSUE TITLE
Design and implement structure to prepare new analysis functionality

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/gpc-optmeowt#204]
Instead of cutting out the cookie functionality, @SebastianZimmeck  suggested adding an internal developer setting (either in code or in extension config) to enable cookies as an extra feature. This would hopefully stop GPC cookies from interfering with future development, while leaving them in for users who want to use the cookie privacy features.

**Comment by SebastianZimmeck** [comment]
Generally, maintaining different branches of software with different functionalities is considered [problematic](https://softwareengineering.stackexchange.com/questions/60393/how-to-maintain-different-customized-versions-of-the-same-software-for-multiple). Instead, as @stanleymarkman is [saying](https://github.com/privacy-tech-lab/optmeowt/issues/204#issue-958440451), **branch-like code organization** is favored. Such organization will make it easier to keep the codebase straight as a whole. 

For our purposes, I imagine we have some hardcoded value that we can change to `1` or `2` to build the extension for each of the two configs. The tricky part may be where two put this logic, and it may be also a lot of work to separate the codebase out accordingly. So, if it is too much work, we can also go with the original plan of removing the cookie logic. Third party cookies will be phased out in browsers anyways. So, ultimately, it will become irrelevant.

**Comment by SebastianZimmeck** [comment]
As we discussed in our call today, we want to add our new analysis functionality. We can use this issue to discuss how to do that. This is not about details but about the conceptual level and view at our codebase as a whole.

### Background

As it currently stands, to opt users out we are sending GPC signals per the [GPC spec](https://globalprivacycontrol.github.io/gpc-spec/). We also place opt out cookies per the [IAB US Privacy String](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md) (e.g., with a value of `1NYN`, which will opt the user out due to the `Y` in the third position of the string). The sending of GPC signals and placing of US Privacy String cookies may interfere with the new analysis functionality. The reason is that the new analysis functionality includes at its core [1]:

1. Checking the existing US Privacy String as it was set by a website (i.e., not by us),
2. Sending a GPC signal, and
3. Checking whether the US Privacy String has been changed (i.e., the site has opted the user out).

For a website that needs to comply with the CCPA (which we ensure by identifying a Do Not Sell link on their homepage), one would expect that the value would change from, e.g., `1NNN` to `1NYN` after sending the GPC signal.

Now, it is easy to see how the current and new functionality can get confusing. For example, instead of the site it may be us placing a cookie with `1NYN` leading us to the conclusion that the site is compliant while it actually may not be.

### What to do?

We need to separate the current functionality from the new functionality so that we can avoid this confusion. There different conceptual approaches:

1. **Radically remove the current functionality**, call it a day with the 2.0.0 release, and move forward  with only the new functionality. This is probably fairly straightforward to do but also means we are no longer an opt out tool but rather an analysis tool.
2. **Have two modes**. In other words, we introduce another level of abstraction in our app where a user select whether they want the old for new functionality. Only what they select is enabled, i.e., if they want analysis mode, everything we currently have is disabled. The new functionality could also be a secret mode of sorts, e.g., if the user pushes a certain button or key combination they get into the new mode.
3. **Have two different builds**. We could also try to address this on the build level. E.g., we (and users compiling from source) could build two different extensions; one with the old functionality and one with the new. This would require to modify the build scripts and codebase.

There are certainly other possibilities as well. The main guideline for us is how we can re-use the code building blocks that we already have. In principle, we already have the building blocks that we need (except for smaller items like identifying Do Not Sell links). The question is how we can organize what we have for our new functionality.

[1] We also place DAA cookies, but as that happens just once at installation time, that functionality is easier to isolate.

**Comment by SebastianZimmeck** [comment]
I looked a bit more in the codebase and my current sense is to go with 2 (Have two different modes). The codebase seems modular enough (though, we probably need to extend that modularity a bit further). Some thoughts:

- We already have functionality for disabling our extension. We can reuse that.
- Add an analysis button to the popup that disables the normal mode and enable the analysis mode
- Upon enabling analysis mode, delete all US Privacy cookies that we have set (can we do that without deleting cookies that we have not set?) and deleting the domain list (may or may not be necessary, not sure; if so, we can warn the user with an alert that the can export their domain list first)
- Add a view to the settings for the compliance analysis functionality (need to create a mockup per issue #157) with analysis results. This could be a list similar to the domain list but without toggles. It could also have an export functionality (reuse the domain list export?)
- Possibly arrange code such that the analysis functionality is only available in Firefox [1].

**Please think about this as well, and let's make a call tomorrow. Then, we need to come up with a more detailed implementation plan.**

[1] Note: depending on what @stanleymarkman finds on issue #148, the analysis functionality may only be possible for Firefox because, different from Chrome, it supports  the [webRequest.filterResponseData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData). I think at a minimum we want to capture US Privacy Strings in headers, including cookies (which are also just headers), and DOM-side implementations. I am not sure whether that is possible without the webRequest.filterResponseData() API.

**Comment by kalicki1** [comment]
I agree with most of what you mentioned @SebastianZimmeck. One of my ideas for making the implementation easier or faster was to have two modes like you explained, however maybe work on adding this functionality for changing modes while the extension is running at a later time and make it a lower priority than simply having a boolean switch in our `defaultSettings.js` file that we can manually change as the developers. This will impact which background script is run when we build, though both will remain in the repo and in the build.

In this case, I agree we can launch the extension with normal mode on by default, but simply change the boolean flag when we want to build for the analysis mode as the developers. This makes it generally hidden to non-developers, but it's easy for us to change modes at any given time by rebuilding. 

I think this will avoid having to figure out how to delete our opt-out cookies in the proper way. If we want users to be able to do this, maybe we can investigate what cookies are deleted so we aren't interfering with the user's experience and add a disclaimer that not all cookies may be deleted properly. In particular I have the DAA and the IAB cookies in mind. As I said however, this can happen at a later date IMO.

**Comment by stanleymarkman** [comment]
One important independent variable we need to account for in the "privacy flag experiment" is accounting for how different websites handle opt-out cookies differently. Cookies are considered fairly impermeant- the user can clear them at will, and many other conditions can lead to cookies being modified or removed locally.

To account for this, we need to determine how websites treat opt-out cookies. Do they treat the state of the cookie in the user as a "ground truth"- immediately respecting removed or modified cookies? Or, via browser fingerprinting (or even some other mechanism) do they retain user privacy settings (falling back to more-restrictive preferences on cookie clear, replacing cookies when modified for a third party, or ignoring removal of cookies).

**Comment by SebastianZimmeck** [comment]
We can still look into this issue @stanleymarkman mentioned because it is good to know generally. But for the time being we assume that a user starts with a clean browser that does not have any cookies. So, there would be no cookies to clear, and US  Privacy String cookies can be set by sites as they normally do it.

@kalicki1 will be looking into a popup banner for a decision asking the user which mode to run (we are going with the two mode idea).

**Comment by SebastianZimmeck** [comment]
Let's write up in somewhat detail which files and how the codebase need to be changes for the new analysis mode. We can doe that here.

**Comment by SebastianZimmeck** [comment]
We have two modes: protection mode and analysis mode.

**Comment by kalicki1** [comment]
@stanleymarkman and I discussed this briefly over the weekend and it seems that, correct me if I'm wrong, the following file structure is what we want to move towards. The files are not specific, they're to give a sense of what needs to be done. 

```
src
|-background
|  |-analysis
|  |  |-background_analysis.js
|  |  |-do_not_sell_links.js
|  |  |-flag_analysis.js
|  |-protection
|  |  |-background_protection.js
|  |  |-events.js
|  |  |-listeners.js
|  |-control.js
```

**Ensuring mode functionality across the extension (specifically, in content scripts via message passing)**

@stanleymarkman also mentioned, which I agree may be the only practical solution, that the content scripts might just have to query the background process for what functionality mode we are running in order to run the in-page processes we need, be it analysis or protection (i.e. fetching well-known info, etc). 

**A global mode control script**

In this mockup, we would have one `control.js` or `backgroundControl.js` file which holds only the logic for triggering each functionality on and off when necessary, via on/off wrappers around the analysis and protection mode modules. I'm imagining we would need a `preinit()`, `init()`, and `postinit()` and similarly for a halt function, just so the processes and properties can be loaded properly and unloaded properly (such as cookies) in the correct order with relation to our listeners. 

**One final naming convention thought** 

I was thinking about how to handle our modes in the code explicitly and was trying to figure out a general way of distinguishing between the "modes" we talk about, i.e. the on/off/domainlist mode and the analysis/protection mode. I thought that we could potentially use `functionality` or `operation` for the latter, and one of `availability`, `activeness`, `ability`, or `readiness` for the former?

Let me know if you all have any thoughts on this.

**Comment by stanleymarkman** [comment]
Excellent writeup, thanks Kuba. My opinion on the naming convention is that the term "activeness" is a pretty standard way to describe this logical flow- function handles could be something like 'setActive(bool isActive)'

**Comment by kalicki1** [comment]
Great, thanks for the review @stanleymarkman! Glad to hear that about the architecture. 

I started working in a local branch on this issue and I’ll push it when most of the changes I’ve made are no longer breaking changes. We can flesh out the structure a little more then and then we should be good to go.

**Comment by SebastianZimmeck** [comment]
That is good, @kalicki1 and @stanleymarkman! A few comments:

- The structure and functionality of the code goes with a certain way of using our extension. **I think we need to be as clear as possible about the different workflows.** At the moment, I can't completely wrap my head around all the possibilities. For example, a user switches from protection mode to analysis mode (or vice versa). What happens now? We tell the user that they cannot do it because the US Privacy String cookies are all set, and we are not deleting them? How does this situation handled by a codebase structured the way you envision it? 
- What is the reason for using names like `functionality` or `operation`? Why not use `analysis-mode` and `protection-mode`?

**Comment by kalicki1** [comment]
@SebastianZimmeck, here's what I'm thinking:

- I know that you intend on having our workflow as clear as possible, but I think that this design will allow us to make modifications to how our mode switches work fairly easy, since everything will be compartmentalized and controlled via a central script. The only problem I see is the one you identified about cookies, which we can make a new issue for.  

That being said, I think this issue falls into two domains. (1) One is getting our analysis functionality up and running without any switching logic, and simply allowing us to build as devs which one we want to run, and (2) two, creating on-the-fly switches for consumers' of the extension. 

1) I can imagine for the time being we simply always initialize the extension via a `defaultSettings` option (i.e., `defaultSettings.functionality = mode.functionality.protection`?) and have the specific modules loaded accordingly on building our extension (via simple function calls that don't contain switching logic from a `backgroundControl.js`) just so we can go ahead and run our tests as devs without having to mess with `protection` mode, as Stanley mentioned above in this thread. 

2) When we have the time, we can flesh out our `backgroundControl.js` file to have listeners for an extension message that triggers a mode switch which would call the corresponding, for example, `protectionHalt()` and `analysisPreinit()` and `analysisInit()` etc. 

I had thought this was outside of the scope of this issue, but I'm thinking that an `analysisPreinit()` switch during runtime for consumers could clear our DAA cookies if that's possible (I'm not sure if that's something we can do off the top of my head), clear all cookies, or like you said, give a warning that IAB/other cookies can't be cleared and it might mess with consumers' analysis. I guess this is the biggest decision to make, and I am fine making this an issue to look into, but I don't particularly have a preference on what we do. I don't think this is a roadblock for the rest of the architecture regardless, maybe someone could give some input here on that as well, unless @SebastianZimmeck you have strong feelings everything should be able to work during normal consumer use via a mode switching mechanism. Either way, I don't think that implementation blocks us from working on other issues. 


- The reason for using names like `functionality` or `operation` is just to categorize what `analysis-mode` and `protection-mode` are. In my eyes it can get confusing what you're referring to when just saying `mode`, such as are you referring to our protection or analysis mode, or whether the extension is on or off? Maybe if we just agree to not use mode to refer to the extension being `enabled`/`disabled`/`domainlisted` this can be avoided, but I'm just bringing it up since we have already done this in the code. I started structuring a new `extensionMode` module something like this: 

```
export const modes = Object.freeze({
	functionality: {
		analysis: 'ANALYSIS',
		protection: 'PROTECTION'
	},
	activeness: {
		enabled: 'ENABLED',
		domainlisted: 'DOMAINLISTED',
		disabled: 'DISABLED'
	}
})
```

Let me know if you do have opinions on any of this or if what I wrote is unclear, I'm happy to go any route as long as we're on the same page.

**Comment by SebastianZimmeck** [comment]
Thanks, @kalicki1! That is good. Let's discuss in a few minutes ...

**Comment by SebastianZimmeck** [comment]
@stanleymarkman mentioned using the anonymous mode for if a user wants to switch from protection to analysis mode. Let's look into whether that is possible. There are different modes for an extension working with anonymous mode.

**Comment by kalicki1** [comment]
I'm currently working on making sure that we can switch between modes as we need during regular extension runtime, and I'm finding that I need to move a fair bit of code around. 

I am making progress, but as a heads up I am refactoring how the old protection-mode background script handles its processes, including: 
- moving persistent data out of protection-mode specific modules and into higher-level control modules, essentially leaving only functions in the protection specific folder
- separating the global `enable`/`disable` extension on/off switch from the 3-way, protection-mode specific, `enable`/`disable`/`domainlist` version into a more robust `isEnabled` global variable for all of OptMeowt and a `isDomainlisted` protection-mode specific variable

**Comment by SebastianZimmeck** [comment]
@kalicki1 is implementing and re-organizing the code already. We do this in this issue and the guiding principles we have discussed here.

**Comment by kalicki1** [comment]
I'm going to use this comment as a working sticky note of To-Do stuff: 

- [ ] Make sure `storageCookies.js` works exclusively with protection-mode (i.e. double check `storage.js`)

**Comment by kalicki1** [comment]
I have gone ahead and opened a pull request on this issue. I will handle the remaining minor bugs in #216. 

Since I have changed how we handle OptMeowt's `on` and `off` states via a new global `enable`/`disable` call and parameter independent of the mode (i.e., an `isEnabled` and `isDomainlisted` parameter, where `isDomainlisted` is protection-mode specific), @stanleymarkman and @OliverWang13 may have to revise some local code depending on what they have worked on. There are also a few other minor structural changes to look out for.
