### ISSUE TITLE
Design and implement analysis logic for sites that process the US Privacy String but do not have a Do Not Sell link

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#224]
Some sites with a Do Not Sell link may not change their US Privacy String. That is clear compliance issue. However, I also found that some sites have a US Privacy String but not a Do Not Sell link. We should flat that situation also as a (potential) compliance issue. Either the site is lacking a Do Not Sell link or they mistakenly implement the US Privacy String (which is specifically for selling; if they are not selling, why are they implementing the String?).

**Comment by SebastianZimmeck** [comment]
We also want to keep track of (in the database, UI, ...) that a site is having this "small" compliance issue (i.e., having a US Privacy String but not having a Do Not Sell link). @stanleymarkman will take the lead on this one.

@OliverWang13 I think the frontend is basically unaffected by this. If not, feel free to chime in. Basically, if there is not a link,  the domain should have a red cross and a `not compliant` label.

**Comment by kalicki1** [comment]
We have discussed this over the past week and I believe we have come to the concensus that if a site somehow processes a US Privacy String but does not have a Do Not Sell link, the whole site should be flagged as non-compliant. 

I believe this issue is most relevant to @OliverWang13 in issue #215. If you have a handle on this and everyone agrees, I think you can go ahead and close this issue, Oliver.

**Comment by kalicki1** [comment]
For the time being, let's treat this case as a normal compliance issue. Let's reopen this issue if we decide to handle this case differently in the future.
