### ISSUE TITLE
Connect frontend to backend in updated main code

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#237]
I am creating this issue to have a concrete place to upload code as I work. I will mainly be taking code from issue #215 and adapting it to work in our new model where we are either in analysis or protection mode. As issue #215 was created a while ago, it is still for Optmeowt while there was only one way to build, and I believe it would be easier to create a new issue that is up to date with main and then fit the frontend I created in.

**Comment by kalicki1** [comment]
Sounds good @OliverWang13. If you think this will replace #215, go ahead and close it.

**Comment by SebastianZimmeck** [comment]
Great, @OliverWang13! As we discussed, it is currently estimated that this issue can be resolved by our meeting next weekend.

**Comment by OliverWang13** [comment]
The Analyzed Domains page has been completed. Next, I will work on implementing the popup. As @kalicki1 brought up, this is very closely linked to switching between protection and analysis modes (Issue #236 ). I will prepare popup.js and popup.html but the completion of the connection is reliant on properly switching between modes.

**Comment by SebastianZimmeck** [comment]
Great!

**Comment by kalicki1** [comment]
I am in the process of cleaning up `popup.js` for @OliverWang13. After this is done, I will move forward with implementing the functionality switch as discussed in issue #236.

**Comment by OliverWang13** [comment]
Current implementation switches modes when the "Protection Mode" tag is clicked. A decision should be made about the run-analysis and download button. Popup performance still seems somewhat inconsistent. I am still having difficulty changing logos and dark mode is temporarily disabled due to this difficulty. Popup spacing is a little wonky but hopefully will not be hard to fix.

**Comment by SebastianZimmeck** [comment]
>  I am still having difficulty changing logos

@kalicki1, please help @OliverWang13 here.

**Comment by kalicki1** [comment]
I was working through the code and I suspect that somewhere in the logic we are accidentally deleting or overwriting the elements that @OliverWang13 is trying to modify. I tested to make sure what we were trying to do wasn't illegal Javascript and it ran fine.

Since I have implemented the foundation for switching between analysis and protection modes in issue #236, I can start work on merging @OliverWang13's frontend into the framework I created and hopefully tease out where in the logic the bug is coming from.

**Comment by kalicki1** [comment]
I managed to get all of @OliverWang13's changes into the main branch and fully connected to the backend we wrote. It seems to be working well based on the tests I ran. Thanks for your work, @OliverWang13, the UI looks good!

Since the main work in this issue is finished, I will go ahead and close it. If we run into any other issues or want to revisit the work that was done on the frontend, we'll be able to go back to branch issue-237 in the future.
