### ISSUE TITLE
Add multilingual user interface

### ISSUE THREAD

**Issue by uDEV2019** [privacy-tech-lab/gpc-optmeowt#239]
It would be great to implement an multilingual user interface.
OptMeowt should be available in the native language of each user, as English is not everyone's thing.

I could provide support for translation into German

**Comment by kalicki1** [comment]
Thank you for opening this issue up, @uDEV2019! Multilingual support is a great idea and we would love to make it happen.

Please feel free to contribute as you wish! If you decide to translate any of our work, go ahead and include those changes here or in a PR. If you include a translation write-up, we'll include the new language when the technical functionality is added. 

If you would like to work right in the codebase, I recommend taking a look at the [last release](https://github.com/privacy-tech-lab/gpc-optmeowt/releases/tag/v2.0.1) commit since the main branch is going through some big, continuous changes at the moment.

**Comment by kalicki1** [comment]
To implement multilingual support we will need to: 

1. Include the translations
2. Implement the infrastructure for changing languages

**Comment by SebastianZimmeck** [comment]
Closing as we do not have the bandwidth at the moment.
