### ISSUE TITLE
Make sure `analysis` logs all domains regardless of data associated with them

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#240]
@OliverWang13 just pointed out to me that some domains that do not have any incoming data, for example, `weebly.com` does not have a DNS link nor a US Privacy String that we can read, do not show up in our records at all. 

Since this does not necessarily mean that these domains do not have to comply with the law, we need to fix this and make sure we do log these domains. At the moment, I only log domains as data associated with them comes in, so we will have to attach a callback to some API (such as `webNavigation.onCommitted`) to record all visited domains.

**Comment by SebastianZimmeck** [comment]
As we discussed today, this issue is about the situation that a site is not subject to the CCPA. In that case we still want to log the result in the backend and show it in the frontend. This can be treated normally with all criteria as `x` (e.g., Do Not Sell link found `x` etc or just GPC signal sent with a checkmark).

@OliverWang13 will take the lead on this and @kalicki1 will assist.

**Comment by kalicki1** [comment]
I just pushed a commit to patch this issue; I ran a few tests and they were all golden. 

Since this issue was fairly small, I will go ahead and close it.
