### ISSUE TITLE
Test updated Validation Set on California IP address

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#245]
My reason for opening this issue is two-fold. Let's discuss methods of running our analysis mode with a California IP address, and then use this issue to update our validation set and keep track of differences between CA tests and tests outside of CA.

- [x] Decide on a method
    - [x] Azure remote desktop
    - [x] Mullvad VPN (suggestion courtesy of @notowen333)
    - [x] Nord VPN
- [x] Update and test validation set outside of CA (Not 100% accurate, for general reference)
- [x] Update and test validation set with a CA IP address
    - [x] Make sure that all domains with `1---` USP string change when using CA address (nypost, etc.) (foxnews does not)
    - [x] Also if domains with `null` USP string change w/ CA address (HuffPost, buzzfeed)

**Comment by OliverWang13** [comment]
I mentioned it in an issue in our other repo, but I have tested NordVPN and it is capable of giving us an IP of Los Angeles. When visiting nypost on a clean browser the USP string does not appear as `1---` anymore, it appears as 1YNN.

**Comment by SebastianZimmeck** [comment]
This issue is the main testing issue with the validation set on the California IP address. Here are important points to consider:

- We decided to test all sites in the validation set using a California IP address via NordVPN. Testing using a non-California address is optional.
- We should not have any implementation issues open that affect the analysis before doing the validation testing. Otherwise, we would need to test again.
- Before we start the validation testing with OptMeowt we should be sure of what the ground truth is for all the sites in the validation set, i.e., whether it has a DNS link and makes use of the US Privacy String/USPAPI (per the California IP address).
- I made a suggestion for the structure of the testing in the [Test Set sheet](https://docs.google.com/spreadsheets/d/19Wi2PaPsEOfiSdeaOEdSNg5QCzJbRmc7f5rHhXYzO6E/edit?usp=sharing). The structure should be the same for the test and validation sets. My preference would be to only have two sheets --- Validation Set and Test Set (unless we also do for CT). Basically, I tried to mirror the four steps of OptMeowt's analysis: (1) DNS Link detection, (2) US Privacy String/USPAPI detection, (3) GPC signal sending, and (4) Second  US Privacy String/USPAPI detection. Along those lines we should structure our testing.
- We want to measure precision and recall from false positives etc. Wikipedia has a [pretty good explanation](https://en.wikipedia.org/wiki/Precision_and_recall#F-measure) if you want to read up on it.
- It will also take some trial and error to establish the testing protocol. It could go something along the lines of (1) take a fresh browser, (2) install OptMeowt, (3) start the VPN, (4) (and now repeat for each site) navigate to testing site, (5) wait until the spinning of the browser tab stops, ... .
- Once you have established the testing protocol, both of you @kalicki1 and @OliverWang13 can split the testing.
- Once we have done this for the whole validation set, we need to take a look at what went wrong and possibly fix issues, and repeat with new validation sites.
- Once we are happy with the validation test, we move on to the test set, which is the set for which we report in the paper.

**Comment by kalicki1** [comment]
Since we are all set with testing the validation set and we are in the process of finishing up what @SebastianZimmeck mentioned above, I will go ahead and close this issue. We can reopen this in the future if need be.
