### ISSUE TITLE
Update domainlist functionality

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#262]
I'm opening this issue to keep #175 a little cleaner. Let's keep track of the MV3 domainlist changes here. Currently I am in the process of slightly changing its format to easily incorporate information about which [Dynamic Rule](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/) each domain is associated with. To allow easy implementation changes, I'll expose it with a simple in-app API. Afterwards, we will need to: 

- [x] Reconnect all the frontend with this new API, ensuring it works (@OliverWang13 possibly)
- [x] Create some function that will regenerate the dynamic rules according to the domainlist if the rules are lost on reinstall, domainlist upload, etc. 
- [x] Create functions that will migrate the old domainlist format to the new one, in preparation for a stable release to the Chrome web store/Firefox Add-ons
- [x] Make sure that a warning is showed when 5000 domains are domainlisted
- [ ] Ensure we sendResponse everywhere ([relevant bug description](https://stackoverflow.com/questions/66618136/persistent-service-worker-in-chrome-extension/66618269#66618269:~:text=If%20you%20also%20use%20sendMessage))

Maybe:
- consider how to surpass the 5000 dynamic rule limit imposed by DNR API
- can we dynamically flip the exclusion list to an inclusion list, vice versa?

**Comment by kalicki1** [comment]
In the last domainlist commit I pushed (Tagging #175), I got a simple internal API to add/remove domains to/from the domainlist and the dynamic ruleset simultaneously. From here, we can refine it a little and begin reconnecting the domainlist functionality to the frontend.

**Comment by kalicki1** [comment]
(Tagging #175) I reconnected the frontend to new domainlist backend API I wrote in `editDomainlist.js` (file name TBD).

I did find a bug that connects the popup 3rd party domain toggles to the 1st party domain. This can be worked out later.

**Comment by SebastianZimmeck** [comment]
> I did find a bug that connects the popup 3rd party domain toggles to the 1st party domain. This can be worked out later.

@kalicki1, is it worthwhile to open an issue on that, or do you keep it on the radar as is?

**Comment by SebastianZimmeck** [comment]
@kalicki1, can you make the checkmarks [above](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/262#issue-1192298667) or change/remove the items to reflect what is still relevant and what not?

**Comment by OliverWang13** [comment]
Below is what Kuba wrote about our situation:

> Data Implementation
Old domainlist model (stored as key/values in IDB)

let domainlist = {
    "duck.com": false,      // Does NOT receive GPC [boolean]
    "google.com": true,     // Receives GPC [boolean]
    "nypost.com": false,
    "dailymail.co.uk": true,
    "example.com": true
}
> New domainlist model (stored as key/values in IDB)
This replaces booleans with nulls as "true" and numbers corresponding to dynamic rule IDs as "falses" from above. Note this reverses the meaning of the previous model's trues/falses.

let domainlist = {
    "duck.com": 887,      // Does NOT receive GPC [number]
    "google.com": null,   // Receives GPC (Universal GPC everywhere rule applies) [null]
    "nypost.com": 1193,
    "dailymail.co.uk": null,
    "example.com": null
}

Kuba then goes ahead to outline his goals for the issue: 

- [ ] Reconnect all the frontend with this new API, ensuring it works
- [ ] Create some function that will regenerate the dynamic rules according to the domainlist if the rules are lost on reinstall, domainlist upload, etc.
- [ ] Create functions that will migrate the old domainlist format to the new one, in preparation for a stable release to the Chrome web store/Firefox Add-ons
- [ ] Make sure that a warning is shown when 5000 domains are domainlisted

So far he has accomplished reconnecting the frontend with the API. From the remaining tasks, we should perhaps discuss whether we still think they are necessary. I think that everything would be doable, but with a significant amount of effort. In order: 
- Create function to regenerate the dynamic rules according to the domainlist
  - I think this is pretty important because it is one of our functionalities to export and import domainlists. Unless we are willing to lose this capability, we should implement it.
- Create functions to migrate the old domainlist format to a new one.
  - This would be nice for our current users, but I am a little unsure about how this would work. When updating the extension on the chrome store, for example, would users lose their domainlist if they did not export it first? If so, this function should be a little easier to create but if not I am not sure how we would access the domainlist.
- Create a warning when 5000 sites are hit.
  - This could be nice to have, but I think that we only need this warning if someone wanted to have 5000 sites AND turn off GPC for all of these sites, which strikes me as a very niche case.

**Comment by OliverWang13** [comment]
@SebastianZimmeck, if you could let me know what you think about this issue, regarding my last comment.

**Comment by SebastianZimmeck** [comment]
> @SebastianZimmeck, if you could let me know what you think about this issue, regarding my last comment.

A crucial point that is not clear to me is _why_ we are doing this refactoring. Are there API changes or other changes that necessitate this refactoring, @kalicki1 and @OliverWang13? It seems quite a bit of work for which we should think carefully if it is necessary.

**Comment by OliverWang13** [comment]
> A crucial point that is not clear to me is why we are doing this refactoring.

The refactoring has already happened as part of the Mv3 switch. The changes @kalicki1 has suggested are to provide further support in the extension to changes that have already been made. The way our extension works in Mv3 is that we have a universal rule that sends the GPC headers to any site that we visit. When a user wishes to stop sending the GPC signal to a site, they tell us and we create a dynamic rule that makes that site an exception. We then store the ID of that dynamic rule in case the user would like to start sending that signal again and we need to know which rule we should delete. In the current version of optmeowt on github, this is how the domainlist is working:

let domainlist = {
"duck.com": 887, // Does NOT receive GPC [number]
"google.com": null, // Receives GPC (Universal GPC everywhere rule applies) [null]
"nypost.com": 1193,
"dailymail.co.uk": null,
"example.com": null
}

**Comment by SebastianZimmeck** [comment]
> Create a warning when 5000 sites are hit.

In either case, I do not think we need this.

**Comment by OliverWang13** [comment]
I think that we also need to implement removing an item from the domainlist.

**Comment by SebastianZimmeck** [comment]
> I think that we also need to implement removing an item from the domainlist.

If that slows us down, I can personally live without that feature. In my view, getting the core functionality working smoothly is the top priority.

**Comment by OliverWang13** [comment]
@sophieeng, I created a function `adaptDomainlist` that should adapt a domainlist from mv2 to mv3. Could you create a button that triggers this function? You will need to import from `storage.js`. Once this button is created, I can do some further testing. My changes are in branch `issue-262`.

**Comment by SebastianZimmeck** [comment]
> eventually this functionality will no longer be needed and can be removed

@sophieeng, good point! I think it would be good if you open an issue reminding us that we need to remove this functionality so that we do not forget. Maybe, we will leave it on for a month or so. Then, create a new release with the functionality removed.

**Comment by OliverWang13** [comment]
This should be dealt with now, so I will be closing this.
