### ISSUE TITLE
Tutorial button not properly navigating

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#328]
If you click the tutorial button in the popup, it should navigate you to the main settings page and then do the tutorial-modal. Currently, if you already have the settings page domainlist tab open for Chrome then it will not switch to the main settings page and show the modal.

This was found in going through the checklist in https://github.com/privacy-tech-lab/gpc-optmeowt/issues/289 for Chrome.

**Comment by OliverWang13** [comment]
This is a tricky issue. It works a lot better when navigating from another site. In that case, it works by switching the setting `TUTORIAL_SHOWN` to `false`, and then running `chrome.runtime.openOptionsPage()`. When our options page opens, it defaults to `settings_view.js`, which then checks the `TUTORIAL_SHOWN` value and shows the tutorial if it is false.

Currently, when on the options page, it sends a message to `settings-view.js` called `SHOW_TUTORIAL`. I think that this perhaps interacts strangely with the `chrome.runtime.openOptionsPage()` or `storage.set(stores.settings, false, "TUTORIAL_SHOWN"` lines. Our darkmode toggle works nearly identically because it uses the same message passing system, but it does not share any of the same issues.

Maybe we would have more success sending a message to `protection.js` and having that communicate with `settings-view.js`. Maybe there is a way to force a reload of the page, making it more similar to when our options page isn't open. Maybe there is a way to create an on change listener that looks for when `TUTORIAL_SHOWN` is changed. Other ideas are also welcome.

**Comment by OliverWang13** [comment]
This is resolved.
