### ISSUE TITLE
Extension Enabling Itself

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#372]
If you disable the extension with the popup, and leave it for around an hour and check on it again, it will have enabled itself again. The issue persists if the extension is disabled in the main settings page.

**Comment by SebastianZimmeck** [comment]
As discussed, @katehausladen will find out if this issue is related to the [known quirk](https://github.com/privacy-tech-lab/gpc-optmeowt/wiki/FAQ-%5C-Known-quirks#why-does-optmeowt-switch-enableddomain-listdisabled-to-domain-list-on-its-own) in the Wiki and update that if necessary. (Maybe, the Wiki quirk is also no longer relevant as @Jocelyn0830 fixed it; so, @Jocelyn0830 will take a look as well and possibly delete or modify.)

Other investigations to understand the issue better are:

1. Does the issue also occur when disabling the extension on the browser's extension page (see screenshot below)? (@katehausladen mentioned that it occurs on both our popup and settings page)
2. Does the issue occur on both Chromium and Firefox?
3. Is this a pure UI issue in the sense that the "enabled UI" is presented but functionally the extension remains disabled (i.e., not opt out signals are being sent)? 

Overall, this is not a big issue. At worst, a user is opted out if they do not want to be opted out (which is better than the other way around). So, if we cannot figure it out, we will add it to the Wiki quirks and move on. Maybe, another one or two weeks at most.

<img width="438" alt="Screen Shot 2022-10-18 at 5 35 47 PM" src="https://user-images.githubusercontent.com/11034003/196549676-f7c10a2a-9636-4c90-a879-c4f9e4efcbf9.png">

**Comment by katehausladen** [comment]
1. The issue does not occur when disabling the extension on the browser's extension page 
2. The issue does not occur when using Firefox
3. It does not appear to be just a UI issue. 
It has been difficult to debug this in chrome because when the console is open, the extension doesn’t seem to enable itself anymore. I will add it to the Wiki quirks.

**Comment by SebastianZimmeck** [comment]
@katehausladen, did you add an entry/updated to the Wiki (quirks/known issues section)?

**Comment by SebastianZimmeck** [comment]
Oh, OK, I saw you mentioned above. Nevermind.
