### ISSUE TITLE
Polyfill Do-Not-Track

### ISSUE THREAD

**Issue by eligrey** [privacy-tech-lab/gpc-optmeowt#418]
[Chrome may remove Do-Not-Track soon](https://bugs.chromium.org/p/chromium/issues/detail?id=931158#c8). This is a useful privacy signal akin to Global Privacy Control. I think OptMeOwt should polyfill `navigator.doNotTrack` preemptively for when/if this happens.

**Comment by sophieeng** [comment]
Looking into this. From what I understand, a polyfill is adding code to implement a feature on browsers that don't natively support the feature. I think we would check the `document` to see if `navigator.doNotTrack` is there and if not then some block of code implementing DNT.

**Comment by SebastianZimmeck** [comment]
Thanks, @sophieeng!

> some block of code implementing DNT

This would be essentially identical to the Sec-GPC header, just it would be a DNT header.

**Comment by sophieeng** [comment]
Oliver and I thought that maybe our extension already created the header and then set it's value like sec-GPC. I tested this by checking `Navigator.globalPrivacyControl` and `Navigator.doNotTrack` with and without the extension installed. The GPC signal with the extension was `true` and without it was `undefined`. The DNT signal with the extension was `null` and without it was `null`. To me this shows that whether or not the extension is working, DNT never has a value, so the extension can never change it to true or false, because DNT does not exist and we don't create it. So I need to implement the signal in the browser and then our extension will change its value depending on what the user wants.

**Comment by eligrey** [comment]
> For future reference, do not inspect the page and go to Console and look for Navigator.doNotTrack because this checks the DOM which we don't change DNT for.

That's what I'm talking about. I'm specifically asking if you think it's worth polyfilling DNT when the JS API is not available. Chrome may be removing this property eventually, and this JS API is used by consent managers so it seems worth it to polyfill this JS API imo.

**Comment by OliverWang13** [comment]
Hey @eligrey, we would be able to set the `navigator.doNotTrack` property similar to how we set the `navigator.globalPrivacyControl` property. Would that in addition to sending the headers be sufficient for implementing DNT? Or would other steps need to be taken if support for DNT was dropped?

**Comment by eligrey** [comment]
Yeah, setting Navigator.prototype.doNotTrack  similarly to Navigator.prototype.globalPrivacyControl is all this would take.

**Comment by OliverWang13** [comment]
This has been resolved and pushed into main, so I will close this issue.
