### ISSUE TITLE
Disable the Topics API

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#428]
Google rolled out the [Topics API](https://developer.chrome.com/en/docs/privacy-sandbox/topics/overview/) as third party cookie replacement. As I see it, OptMeowt should disable the Topics API upon install. Here is an [override for Chrome Settings](https://developer.chrome.com/docs/extensions/mv3/settings_override/), which may be helpful to make such setting. 

I'd say, for the time being, we can just disable. We do not need to have a UI for enabling/disabling it. And if people turn it on via their browser, maybe from that moment on the browser setting governs (also for turning it on/off multiple times). Though, I am flexible on the exact implementation based on how the override works.

Disabling the Topics API is only relevant for Google Chrome (and, possibly, some other Chromium browser) but not for Firefox (and privacy-preserving Chromium browsers like Brave). So, only the Chrome version would need to change (I am not exactly sure how to distinguish among Chromium browsers, but maybe it is OK if there is a silent fail or an exception is caught for those Chromium browsers that do not support the Topics API).

On a side note, eventually, we can also remove the third party opt out cookie placing, but that is maybe in two years or so. During this transition phase we can leave that functionality in.

@Jocelyn0830, if anything is unclear, we can discuss more.

**Comment by Jocelyn0830** [comment]
I just started to look at this issue. I was confused since this guide only talks about how to override settings of Homepage, search provider, and startup pages. After exploring a little more, I found [`privacy`](https://developer.chrome.com/docs/extensions/reference/) on [this site](https://developer.chrome.com/docs/extensions/reference/) that might be what we want. I will look more into it. Just document my findings here.

**Comment by Jocelyn0830** [comment]
[This site](https://developer.chrome.com/docs/extensions/reference/privacy/#property-websites-topicsEnabled) provides useful api information for disabling topics api. I created a new branch for this issue and has been experimenting with the api provided. The current issue I face is how to test if topics api is successfully disabled.

Thus, I found [another extension](https://privacybadger.org/) that claims in their document they turned off topics api by default upon installation, same as what we want. I looked into their source code and it seemed to me that they used a relatively complex approach rather than the api mentioned above to turn off the topics api. Details could be found [here](https://github.com/EFForg/privacybadger/pull/2888). I still need more experimenting and testing.

**Comment by SebastianZimmeck** [comment]
> The current issue I face is how to test if topics api is successfully disabled.

Great!

**Comment by Jocelyn0830** [comment]
I worked on testing if topics api is successfully disabled. I found out that if we include this in our script
```
if (document.browsingTopics) {
  console.log(true)
} else {
  console.log(false)
}
```
It seems to indicate whether topics api work or not. However it appears true most of times I tested on websites. Thus,  I looked into how Privacy Badger turns off topics api. It appears to me they do this through adding/modifying `permissions policy header`. Here is an explanation from Google's topics api document:
> You can opt out of topic calculation for specific pages on your site by including the Permissions-Policy: browsing-topics=() [Permissions-Policy](https://developer.mozilla.org/docs/Web/HTTP/Headers/Feature-Policy) header on a page to prevent topics calculation for all users on that page only.

It seems that if we set this on every page the user visits, the topics api is successfully blocked. I spent quite some time integrating it with our current header setting (w/o interrupting our main functionality). However, the above test mentioned is still not passed. I installed Privacy Badger and found it seemed that they didn't pass the test as well. As a result, since this is not urgent, I will probably stay with the brute force testing method: install optmeowt and browse for several days and check if topics appear.

**Comment by SebastianZimmeck** [comment]
Thanks, @Jocelyn0830! 

>  I installed Privacy Badger and found it seemed that they didn't pass the test as well.

Do they have a repo where we could post an issue and ask?

**Comment by SebastianZimmeck** [comment]
Also, if we can't turn off the Topics API, a stop gap solution is to display upon extension install a popup with a screenshot explaining how to turn it off. But before we go there we should make sure that there is really no way to turn it off programmatically.

**Comment by SebastianZimmeck** [comment]
@dharb provided the [DuckDuckGo Privacy Essentials solution](https://github.com/duckduckgo/duckduckgo-privacy-extension/blob/main/shared/js/background/events.js#L257).

**Comment by Jocelyn0830** [comment]
Added `permissions-policy` header. Seems to do the job.
